/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#041632',
        'primary-container': '#1b2b48',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#b7c7eb',
        secondary: '#006a65',
        'secondary-container': '#6bf8ee',
        'secondary-fixed': '#6bf8ee',
        'secondary-fixed-dim': '#48dbd2',
        tertiary: '#06172a',
        'tertiary-container': '#1c2c40',
        background: '#f7f9fb',
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container': '#eceef0',
        'surface-container-low': '#f2f4f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#091b37',
        'on-primary-fixed-variant': '#374765',
        'on-primary-container': '#8393b5',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#00201e',
        'on-secondary-fixed-variant': '#00504c',
        'on-secondary-container': '#00716b',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#0b1c30',
        'on-tertiary-fixed-variant': '#38485d',
        'on-tertiary-container': '#8393ac',
        'on-surface': '#191c1e',
        'on-surface-variant': '#44474d',
        'on-background': '#191c1e',
        outline: '#75777e',
        'outline-variant': '#c5c6ce',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#b7c7eb',
        'surface-tint': '#4f5e7e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        gutter: '24px',
        base: '8px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-xl': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-lg-mobile': ['"Hanken Grotesk"', 'sans-serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'label-sm': ['"Geist"', 'sans-serif'],
        'label-xs': ['"Geist"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.0', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-xs': ['12px', { lineHeight: '1.0', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
